### ISSUE TITLE
Preferences does not load the existing preference when showing screen

### ISSUE THREAD

**Issue by tbd-develop** [tbd-friends/water-drink-water#1]
When you navigate away from preferences and return, the value resets to 0 even though the database has the value stored. 

Expected Behavior; Should show the value last entered

Test;
- Navigate to Preferences, enter a value of 64
- Validate the database has a preference of 64 target fluid ounces
- Navigate to Log
- Navigate back to Preferences
- Value should show 64

**Comment by Junicus** [comment]
Looking at this, it looks like a new endpoint will be needed to get the preferences from the api,  additionally the preferences page needs to be initialized from that endpoint.

**Comment by tbd-develop** [comment]
As we added timezone offset to the preferences since this was done, we should also load this preference and display options for selecting timezone.
