### ISSUE TITLE
Peferences need a new GET endpoint

### ISSUE THREAD

**Issue by Junicus** [tbd-friends/water-drink-water#11]
This endpoint is needed for retrieving the preferences from the UI.

Related to #1

**Comment by Junicus** [comment]
Looking further into this issue there needs to be an update to the ConsumptionService and the ConsumptionRepository.

Thinking that new there are multiple methods that deal with preferences in the ConsumptionRepository and ConsumptionService, would a service/repo for preferences be more convenient?

**Comment by tbd-develop** [comment]
It's probably better to have a discussion about more generalized repositories, whether they are needed etc and what patterns are worth putting in place before proceeding here. I agree, the code doesn't need to be in the consumption pieces.

**Comment by Junicus** [comment]
lets talk some more about separating the preferences api, should we refactor the code before this pr, or should it be a separate issue and build on this pr
