### ISSUE TITLE
Display Daily Progress

### ISSUE THREAD

**Issue by tbd-develop** [tbd-friends/water-drink-water#22]
we need to consume /api/consumption and display the progress towards our daily water consumption goal

**Comment by Junicus** [comment]
there is a disconnect in the view that logs the consumption Log.razor and the components that display the percentage.

When the logconsumption method is call, the components that need to display the status don't know that there is a change and don't update until a refresh when they consume the getconsumptionpercentage.  

We need a common place to store that state, a StateProvider component that provides the state as a cascading parameter might be a good solution, that state provider would also expose an api for logging consumption and settings goal preferences.  It has an instance of the userservice to communicate with the api, anytime the state needs update through the api it can also update the state, and all children that consume that state will update

**Comment by Junicus** [comment]
another option is to change the UserService to also keep state for this, but then UserService would be doing too much, a component or a separate state service feel like a better choice
