### ISSUE TITLE
I want to be able to see the logs for a date

### ISSUE THREAD

**Issue by tbd-develop** [tbd-friends/water-drink-water#34]
On the Log screen below the current consumption capture, I should see a log of the water I have consumed. It should default to the current date, but should allow me to select another date in the past. 

Consume the log api, display the consumption in time order

Depends on #33 

![Wonderful_Mockup_WDW_Logs](https://github.com/tbd-friends/water-drink-water/assets/986409/157437b2-8c59-450e-b0f8-cb8d0a625d48)

**Comment by CodeItQuick** [comment]
I typically start with the frontend, can I grab this one first?

Values will be hardcoded on the API/on the request
