### ISSUE TITLE
Water consumption doesn't show on first login

### ISSUE THREAD

**Issue by tbd-develop** [tbd-friends/water-drink-water#41]
![image](https://github.com/tbd-friends/water-drink-water/assets/986409/a87a7a42-80ea-4693-a13d-75cd41883aa5)

When you first login to the application, the current consumption doesn't update and stays at 0%.

Steps to recreate;

- Run Application
- Log Consumption
- Logout
- Stop Application
- Run again
- Login
- Consumption Percentage remains 0%

**Comment by CodeItQuick** [comment]
dota2attitude here - can I take this one?

**Comment by CodeItQuick** [comment]
Oh Wesley beat me to it, I'll grab another

**Comment by tbd-develop** [comment]
Closing as fixed in PR #48
